# Default values for funcx_endpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
funcXServiceAddress: https://api2.funcx.org
image:
  repository: funcx/kube-endpoint
  tag: main
  pullPolicy: Always

workerDebug: false
workerImage: python:3.6-buster
workerInit: pip install globus-compute-endpoint>=0.2.0
workerNamespace: default
logDir: /tmp/worker_logs

rbacEnabled: true
nameOverride: globus-compute-endpoint

initMem: 2000Mi
maxMem: 16000Mi
initCPU: 1
maxCPU: 2

initBlocks: 0
minBlocks: 1
maxBlocks: 100
maxWorkersPerPod: 1
maxIdleTime: 3600

detachEndpoint: true

endpointUUID:
